### ISSUE TITLE
Authenticate Pings as Direct/Private Messages

### ISSUE THREAD

**Issue by miklb** [williammck/hubot-basecamp-3#1]
First, thank you so much for the work on this. I set it up last night and it is a great start. 

My next goal will be to use the callback Url for the bot to send messages, i.e. extended GitHub integration. Any thoughts on best way to accomplish this? If I figure it out, I will certainly send a pull request.

Unrelated, any thoughts on how to create a private message with the bot? A toggl script I looked at requires a user to send API token as a PM, and Hubot isn't recognizing a direct Ping conversation with the bot. Unless I'm missing something.

Again, I can't thank you enough for releasing this adapter.

Cheers.

**Comment by williammck** [comment]
Hey! Glad this worked for you.

Sorry for the delay, for some reason I wasn't watching this repository and just now noticed this...

1. I'd like a bit more clarification there, as I'm not sure what exactly your use case is.
2. You should be able to start a Ping with the bot, seems to work fine on my test instance.

**Comment by miklb** [comment]
No worries! When I tested it back then, I tried sending the command to the bot as a ping, but the toggl plugin (which I think was more meant for Slack) didn't recognize the ping as a PM, thus couldn't pass the key necessary. I haven't revisited the experiment myself, but a good time to do so.

**Comment by miklb** [comment]
Finally™ getting around to revisiting this, and from what I can tell ,the `hubot-toggl` script is checking if room name matches the user name https://github.com/yamadapc/hubot-toggl/blob/master/lib/script.js#L79

Either way, it doesn't recognize that you are in Ping. I'm not even sure what I meant by "use the callback Url for the bot to send messages"

If you have any suggestions on how to work around that, I'd appreciate your time.

**Comment by miklb** [comment]
An issue has since been created regarding the DM/PM in the `hubot-toggl` repo https://github.com/yamadapc/hubot-toggl/issues/27

**Comment by williammck** [comment]
Interesting!

There is no specific way to determine a "room" in the [Basecamp 3 chatbot API](https://github.com/basecamp/bc3-api/blob/master/sections/chatbots.md), so I can totally see a valid reason for making the room equal to the user name.

I'm a bit busy at the moment, but might have some time to add that this weekend.

**Comment by miklb** [comment]
That would be great. Even if you can point me in the right direction, I could try sending a pull request.

**Comment by williammck** [comment]
I've applied a fix in commit 000f08e, v1.0.2 is now available in npm.

Let me know if you encounter further issues with it.

**Comment by miklb** [comment]
Worked great, thanks!
